version: '3'

networks:
 sorting:

services:
 nginx:
  image: nginx:stable-alpine
  container_name: nginx
  ports:
   - "8088:80"
  volumes:
   - ./:/var/www/html
   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  depends_on:
   - php
  networks:
   - sorting

 php:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: php
  volumes:
   - ./:/var/www/html
  ports:
   - "9000:9000"
  networks:
   - sorting